name: Flutter APK Build

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get
        working-directory: pawfect_care

      - name: Build Flutter APK
        run: flutter build apk --release
        working-directory: pawfect_care

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          files: pawfect_care/build/app/outputs/flutter-apk/app-release.apk
          name: Release pawfect_care v1.0.${{ github.run_number }}
          tag_name: pawfect_care-v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
